### ISSUE TITLE
Error Creating Dev Drive

### ISSUE THREAD

**Issue by ddieppa** [microsoft/devhome#1295]
### Dev Home version

0.200.170.0

### Windows build number

10.0.25905.1000

### Other software

OS Build Version: 10.0.25905.1000.amd64fre.rs_prerelease.230707-1739
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Go to System>Storage>Disks & volumes
click on Create Dev Drive
Create new VHD
Follow the steps to create the VHD
Wait until the creating process finish

### Expected result

Create the Dev Drive

### Actual result

Error:
Unable to load data. Please try again.
REFS is not supported

### Included System Information

Physical Memory: 15.85GB (6.16GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by bbonaby** [comment]
@ddieppa looks like this is actually an issue within the Windows Settings app and not the Dev Home app. There was an issue with the Dev Drive feature in 10.0.25905.1000.amd64fre.rs_prerelease.230707-1739. However, this should now be resolved after a reboot. If not, please file a bug via the Windows Feedback hub app. You can launch this app via Window key + f

Thanks!

**Comment by sander1095** [comment]
I still have this same issue on the latest version of Windows 11. I have had this for the last 6+ months
