### ISSUE TITLE
Provision to create a Dev Drive does not appear in Settings

### ISSUE THREAD

**Issue by jayanzth** [microsoft/devhome#901]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Steps to reproduce the bug

1. Navigate to the Introducing Dev Home page
2. Click on Create Dev Drive button under the Create a Dev Drive card group
3. This should redirect you to the Disks and Volumes page in Settings
4. The supposed to be Create Dev Drive feature is absent.

### Expected result

I should have got a screen that contains the provision like the one in the image below

![dev-drive-create](https://github.com/microsoft/devhome/assets/93752903/895d2fa2-46b8-4251-990a-d157384c4399)

### Actual result

On my PC, the feature was not available

![image](https://github.com/microsoft/devhome/assets/93752903/b3875da9-215d-4469-8ba8-4d5fb8b16bd9)

### Included System Information

OS : Windows 11 Home Single Language
Version: 10.0.22621 Build 22621
Processor: AMD Ryzen 5 4600H with Radeon Graphics, 3001 Mhz, 6 Core(s), 12 Logical Processor(s)

### Included Extensions Information

Dev Home GitHub extension (came pre-installed with application)

**Comment by Spatacoli** [comment]
@jayanzth you need to be in the Dev channel of the Windows Inisder Program to see this option. Once there make sure you have build 23466.1001 or newer and the option will appear.

For more information check the [prerequisites](https://learn.microsoft.com/en-us/windows/dev-drive/#prerequisites) for Dev Drive.

**Comment by jayanzth** [comment]
The issue has been resolved. Dev channel of the Windows Insider Program is a requirement for this option to be enabled. Thanks to @Spatacoli for helping with this issue!

**Comment by perrylets** [comment]
I'm on the Dev channel and my current build is 23506.1000 ni_prerelease and I still have the same problem. I'm also using Windows Pro if that helps.
